name: CI

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21.x, 1.20.x, 1.19.x]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Install gocode
      run: go install github.com/mdempsky/gocode@latest
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Lint
      run: make lint
